## Requirements

In [1]:
import datetime
import pathlib
import pandas as pd
import polars as pl

## Reading CSV data

The file `large_data_0001.csv` is not part of this repository due to its size.  It can be generated using the `create_csv_data.py` script.  However, note that this takes a couple of minutes for 2,500,000 rows and 100 columns.

In [2]:
file_name = 'large_data_0001.csv'
assert(pathlib.Path(file_name).exists())

In [3]:
%time df_polars = pl.read_csv('large_data_0001.csv', try_parse_dates=True)

CPU times: user 2.65 s, sys: 1.98 s, total: 4.63 s
Wall time: 516 ms

In [4]:
%time df_pandas = pd.read_csv(file_name, parse_dates=['timestamp',])

CPU times: user 942 ms, sys: 473 ms, total: 1.42 s
Wall time: 1.36 s

Note that polars is clearly much faster and using multiple threads as the CPU time exceeds the walltime by a factor of 4.

In [5]:
df_pandas.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 101 entries, timestamp to C100
dtypes: datetime64[us](1), float64(100)
memory usage: 192.6 MB

In [6]:
df_polars.estimated_size()

202000000

The size of the dataframes in memory is comparable.

The data consists of a single column with timestamps, and 100 columns of random double precision floating point values.

## Group by

To compare performance

In [7]:
days_pandas = df_pandas.groupby(df_pandas.timestamp.dt.day).mean().drop('timestamp', axis=1)

In [8]:
days_pandas

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C91,C92,C93,C94,C95,C96,C97,C98,C99,C100
timestamp,,,,,,,,,,,,,,,,,,,,,
27,0.404696,0.261931,1.287319,0.612213,0.681026,0.742812,0.896647,0.862290,0.460183,0.629668,...,2.236251,1.744978,1.778563,0.818831,0.138233,0.585064,0.262821,1.091273,-0.630481,1.000678
28,0.877083,-0.794693,-0.754304,2.214836,-0.506672,-1.526856,1.776685,0.837315,-1.307134,-0.427087,...,3.983528,2.687888,1.220114,0.155312,-0.594783,-0.694168,-1.472570,0.469418,-3.537292,1.937989
29,0.324231,-0.821355,-2.187812,1.259114,-0.450201,-3.382532,3.261461,1.602604,-1.831738,-1.289988,...,5.924970,4.773395,-1.383860,2.498419,-2.194429,-0.774803,-1.095649,0.732430,-4.382272,2.260150
30,0.782333,-1.956636,-3.251395,0.568219,-0.098479,-5.547958,3.948161,-0.269686,-2.396618,0.119764,...,6.220640,4.786257,-1.703247,4.050323,-2.317972,0.849521,-1.134187,0.548018,-5.121591,3.224718

In [9]:
days_polars = df_polars.group_by_dynamic('timestamp', every='1d').agg(pl.exclude('timestamp').mean())

In [10]:
days_polars

shape: (4, 101)
┌─────────────┬──────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ timestamp   ┆ C1       ┆ C2        ┆ C3        ┆ … ┆ C97       ┆ C98      ┆ C99       ┆ C100     │
│ ---         ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---      ┆ ---       ┆ ---      │
│ datetime[μs ┆ f64      ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64      ┆ f64       ┆ f64      │
│ ]           ┆          ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
╞═════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ 2026-10-27  ┆ 0.404696 ┆ 0.261931  ┆ 1.287319  ┆ … ┆ 0.262821  ┆ 1.091273 ┆ -0.630481 ┆ 1.000678 │
│ 00:00:00    ┆          ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ 2026-10-28  ┆ 0.877083 ┆ -0.794693 ┆ -0.754304 ┆ … ┆ -1.47257  ┆ 0.469418 ┆ -3.537292 ┆ 1.937989 │
│ 00:00:00    ┆          ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ 2026-10-29  ┆ 0.324231 ┆ -0.821355 ┆ -2.187812 ┆ … ┆ -1.095649 ┆ 0.73243  ┆ -4.382272 ┆ 2.26015  │
│ 00:00:00    ┆          ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ 2026-10-30  ┆ 0.782333 ┆ -1.956636 ┆ -3.251395 ┆ … ┆ -1.134187 ┆ 0.548018 ┆ -5.121591 ┆ 3.224718 │
│ 00:00:00    ┆          ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
└─────────────┴──────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴──────────┘

In [11]:
%timeit days_pandas = df_pandas.groupby(df_pandas.timestamp.dt.day).mean().drop('timestamp', axis=1)

47.4 ms ± 4.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [12]:
%timeit days_polars = df_polars.group_by_dynamic('timestamp', every='1d').agg(pl.exclude('timestamp').mean())

42.9 ms ± 3.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [13]:
%timeit df_pandas['avg'] = df_pandas[[f'C{i}' for i in range(1, 101)]].mean(axis=1)

<magic-timeit>:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

133 ms ± 13.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [14]:
%timeit df_polars.select(pl.all(), pl.mean_horizontal(pl.exclude('timestamp')).alias('avg'))

40.7 ms ± 2.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

On these operations, polars is faster as well.